@startuml Flow3
!include Tubivi_Praxis.puml

start
partition "Profile" {
  :User presses settings button;

  partition "Settings" {
  :Display settings modal;
  :User presses Edit Featured Achievement button;
  :Switch to edit mode;
  :User selects at most 3 achievements to feature/showcase;

  if (User presses back button) then (yes)
    :Cancel edits;
    :Dismiss all achievements modal;
    stop
  else
    :User presses save button;
    :Update db;
    :Toggle edit mode;
  endif

  :User presses any achievement;
  :Display achievement detail modal;

  :User presses back button;
  :Dismiss all achievement modal;
}
}